### ISSUE TITLE
Bugs in first almost complete version

### ISSUE THREAD

**Issue by polarkernel** [vvoovv/pml#8]
I committed a first almost complete version of the translator. However, it is only very few tested. I propose to let it stay as is for a while and to collect found bugs in this issue, as long as they are not vital for the application.

**Comment by vvoovv** [comment]
The great achivement! Congratulations!

I commented the [line](https://github.com/vvoovv/pml/blob/master/PML2PythonTranslator-Dev-I/PML2PythonTranslator.py#L6) with the import of _testListener_ out, since there was no module _testListener_

**Comment by vvoovv** [comment]
I suggest not to use the JSON structure in PML

```json
styles : {
    "mid rise residential zaandam": [
    ...
    ]
}
```

I suggest to introduce statements in PML:
* a statement to name a set of style blocks
* import (to be defined later)
* include (to be defined later)

It could be like this:
```json
@name "mid rise residential zaandam";
// style blocks for that style are place below till the next statement @name
{
...
}
{
...
}
// next style is defined
@name "high rise"
{
...
}
{
...
}
```

**Comment by vvoovv** [comment]
If no `@name` statement is given, the name of the style is taken from the file name without extension.

**Comment by vvoovv** [comment]
What do you think?

**Comment by polarkernel** [comment]
@name is easy to implement. Just tell how you like to have this language, if you have other propositions, I have enough experience with ANTLR4 now so that I will be able to implement it.

**Comment by polarkernel** [comment]
We need a concept for exception handling. I propose to implement a boolean into the demo program PML2PythonTranslator that gets false when the parser detects syntax errors. Additionally a string, that holds the error messages of the parser instead of writing them to stderr. Depending on the application it would be bad when for instance the Python interpreter of Blender crashes, because the user forgot a semicolon in PML.

**Comment by polarkernel** [comment]
Any proposition how _PerBuilding()_ should look in PML?

**Comment by vvoovv** [comment]
> @name is easy to implement. Just tell how you like to have this language, if you have other propositions, I have enough experience with ANTLR4 now so that I will be able to implement it.

So let's have the _@name_ statement instead of JSON syntax.

I am looking forward to the day when it will possible to write a facade style in PML instead of Python and change the style without restarting Blender.

**Comment by vvoovv** [comment]
> We need a concept for exception handling. I propose to implement a boolean into the demo program PML2PythonTranslator that gets false when the parser detects syntax errors. Additionally a string, that holds the error messages of the parser instead of writing them to stderr. Depending on the application it would be bad when for instance the Python interpreter of Blender crashes, because the user forgot a semicolon in PML.

I agree. The error message will be shown to a user in Blender popup panel.

**Comment by vvoovv** [comment]
> Any proposition how _PerBuilding()_ should look in PML?

Just _perBuilding(..)_?

**Comment by vvoovv** [comment]
I've just removed the file _example.pml_ from the top folder and moved all files to the top folder.

Git tags can be used to mark the stages of the development

**Comment by vvoovv** [comment]
> > Any proposition how _PerBuilding()_ should look in PML?
> 
> Just _perBuilding(..)_?

Or _per_building(..)_ ?

**Comment by polarkernel** [comment]
Yes, I like _per_building_. It fits to _random_normal_, _random_weighted_ and _use_from_.

**Comment by polarkernel** [comment]
> If no `@name` statement is given, the name of the style is taken from the file name without extension.

This is diffcult (but feasible) to solve, as the parser runs after the lexer and then, the name of the file is no more available. The filename would have to be passed to the _PythonCoder_ in any case. What would be its application? If a user writes a PML file, shouldn't he know already its name?

**Comment by vvoovv** [comment]
If a PML file contains only one style, then there would be a duplication of style names (in the _@name_ statement and in the file name). So I suggest that the statement _@name_ is not obligitary.

On a separate note. If the content of a PML file is supposed to be included in another file, then the style name is not need.

**Comment by polarkernel** [comment]
To be sure that I understod correctly, let me sketch an example. Let the PML code be
```
@name "mid rise residential zaandam";
    Footprint { ... }
    ....
@name "high rise mirrored glass";
    ...
```
then the translator should produce
```
styles = {
    "mid rise residential zaandam": [
        Footprint ( ... )
        ... ]
    "high rise mirrored glass" : [
    ... ]
}
```
In the case of no @name statement, the PML file would just look like
```
Footprint { ... },
Facade{ ... }
```
and the translator should then produce (for this file with only one style definition)
```
styles = {
    "nameOfPMLfileWithout Extension": [
        Footprint ( ... ),
        Facade( ... )
        ... ]
}
```
Did I get it?

**Comment by vvoovv** [comment]
A typical use-case is to add entries from a PML file to the Python dictionary of styles which is referred below as _global dictionary of styles_.

(1)
There is one or more _@name_ in the PML file.

The translator outputs a Python dictionary:
```
styles = {
    "mid rise residential zaandam": [
        Footprint ( ... )
        ... 
     ],
    "high rise mirrored glass" : [
    ... 
    ]
}
```
The application iterates through the entries of _styles_ and adds them to the _global dictionary of styles_.

(2)
There is no _@name_ in the PML file.

The translator outputs a Python list of style blocks:
styles = [
    Footprint(...),
    ...
]

The application checks if _styles_ is a Python list or dictionary. In the former case see (1). In the latter case the new entry is added to the _global dictionary of styles_ with the key _Filename without extension_.

**Comment by polarkernel** [comment]
OK, now I got it, thanks. I updated and commited the code, @name should work now.

> I am looking forward to the day when it will possible to write a facade style in PML instead of Python and change the style without restarting Blender.

This will be a good day. Good luck!

**Comment by vvoovv** [comment]
The closing [square bracket](https://github.com/vvoovv/pml/blob/master/example.pml#L218) seems not to have the preceding counterpart. The translator doesn't compain about this fact.

**Comment by vvoovv** [comment]
What is wrong with this PML? It doesn't output the footprint.

[example2.txt](https://github.com/vvoovv/pml/files/4672482/example2.txt)

Github didn't let to attach the file with the extension _pml_. So I changed the extension to _txt_.

**Comment by polarkernel** [comment]
Corrected several bugs in grammar. _example.pml_ updated. All should run now.

**Comment by vvoovv** [comment]
Strange output for _claddingMaterial_:

```python
                claddingMaterial = Value(Alternatives(
                    FromAttr("building:material", D),
                    FromAttr("building:material", i),
                    RandomWeighted( (("brick",1),("plaster",1)) )
                ))
```

I added the input file to to the repo: [example2.pml](https://github.com/vvoovv/pml/blob/master/example2.pml)

**Comment by vvoovv** [comment]
I suggest to delete a pair of round brackets for `random_weighted(..)`:
`random_weighted( (brick, 1), (plaster, 1) )`
instead of
`random_weighted( (brick, 1), (plaster, 1) ) )`

Those brackets are still needed in Python.

**Comment by vvoovv** [comment]
Another proposed change:
`@meta{...}`
instead of
`meta{...}`

**Comment by vvoovv** [comment]
Is conditional already supported by the translator?
`random_weighted( (concrete, 1), (gravel, 1) ) if item.footprint["roofShape"] == "flat"`

`footprint["roofShape"]` should be substituted for `footprint.getStyleBlockAttr("roofShape")` in Python.

**Comment by polarkernel** [comment]
> Strange output for claddingMaterial:

"building:material" was not in _Dictionaries_. I added now an exception for this case, so that the dictionary of attributes can be completed when this case arises again. I don't have a list of all possible attributes with value types and ranges. Maybe you have?

> I suggest to delete a pair of round brackets for random_weighted(..)

Done.

> @meta 

Implemented.

> Is conditional already supported by the translator?

Yes, but I changed the syntax a little bit, because your proposition was very difficult to integrate in the grammar. The syntax is now like this:

```
if ( item.footprint["roofShape"] == "dome" ) glass;
```

All these changes are already commited now.

**Comment by vvoovv** [comment]
We can fill the dictionary of OSM tags on demand as they are needed in the style.
I've just added _building:colour_ to the dictionary.

**Comment by vvoovv** [comment]
example2.pml doesn't work for me again.

**Comment by polarkernel** [comment]
> example2.pml doesn't work for me again.

Shouldn't _item_ have a specifier, like _item.footprint_, _item.parent_ or _item.self_?

**Comment by vvoovv** [comment]
The possible values for a color constant are:
* a word (e.g. white, green, lightyellow)
* a hex string with 3 or 4 components (e.g. `#ff00ff` or `#ff00ff00`)
* a _rgb_ tuple in the form `rgb(120, 255, 100)`, the components of the tuple are integers between 0 and 255
* a _rgba_ tuple in the form 'rgba(120, 255, 100, 0.5)', the _rgb_ components of the tuple are integers between 0 and 255, the _a_ component of the tuple is a float between 0.0 and 1.0

The color should be translated to a Python tuple with 4 value between 0.0 and 1.0
The code for color translation including a list of colors and all needed functions is located [here](https://github.com/vvoovv/blender-osm/blob/dev/grammar/value.py#L284)

**Comment by vvoovv** [comment]
> > example2.pml doesn't work for me again.
> 
> Shouldn't _item_ have a specifier, like _item.footprint_, _item.parent_ or _item.self_?

`item.self["building:material"]` is actually `item["building:material"]`. That longer form looks odd for me. Would it be difficult to use the form `item["building:material"]`?

**Comment by polarkernel** [comment]
So
```
item["claddingMaterial"] == "brick"
```

would be translated to
```
lambda item: item.getStyleBlockAttr("claddingMaterial") == "brick"
```

Should be feasible, let me see.

**Comment by vvoovv** [comment]
> So
> 
> ```
> item["claddingMaterial"] == "brick"
> ```
> 
> would be translated to
> 
> ```
> lambda item: item.getStyleBlockAttr("claddingMaterial") == "brick"
> ```
> 
> Should be feasible, let me see.

yes

**Comment by polarkernel** [comment]
item["claddingMaterial"] should work now.

**Comment by vvoovv** [comment]
File example2.pml. Stuck again.

**Comment by polarkernel** [comment]
> File example2.pml. Stuck again.

Corrected. Hope it produces not too much side effects.

**Comment by vvoovv** [comment]
File example2.pml. Now problem with the condition.

**Comment by polarkernel** [comment]
> File example2.pml. Now problem with the condition.

This will take some time. Logical operators are not yet implemented in the grammer, only relational operators. Didn't find an example before.

**Comment by vvoovv** [comment]
Ok. I'll wait.

**Comment by vvoovv** [comment]
Round brackets are possible in a condition to change the order of logical expressions.

**Comment by polarkernel** [comment]
> Ok. I'll wait.

Should work now. Conditions may use _boolean_, _comparison_ and _arithmetic_ operators and round brackets. Was a very long debugging period until I found that an _identifier_ "eats" tokens like _and_, _or_ or _not_, if these are not declared on top of the lexer rules. However, I have written very comfortable debugging tools now ;-)

**Comment by vvoovv** [comment]
Problem with the [condition](https://github.com/vvoovv/pml/blob/master/example2.pml#L51).
Also _curtain_wall_ should be translated to _CurtainWall_.
It can be a general rule, that a letter succeeding the underscore character should be capital cased.

**Comment by polarkernel** [comment]
>Problem with the condition.
> It can be a general rule, that a letter succeeding the underscore character should be capital cased.

Both issues solved

**Comment by vvoovv** [comment]
The output isn't correct:
```python
Facade(
        condition = lambda item: FromStyleBlockAttr("claddingMaterial",FromStyleBlockAttr.Footprint) == "glass",
        markup =  [
            CurtainWall()
        ]
)
```

It should be
```python
Facade(
        condition = lambda item: item.footprint.getStyleBlockAttr("claddingMaterial") == "glass",
        markup =  [
            CurtainWall()
        ]
)
```

_FromStyleBlockAttr(..)_ is only used inside _Value(..)_ if it is desired to set the value of an attribute to the value of another attribute.

**Comment by polarkernel** [comment]
OK, fixed.

**Comment by vvoovv** [comment]
The style _high rise_ is nearly ready. A problem with the last attribute.

**Comment by polarkernel** [comment]
> A problem with the last attribute.

The logical operator _in_ added. Using expressions for smoothness attributes required a deep hack. Usually, parsers care about syntax, but not semantics. The last time I encountered variable names that changed a context was in the early 1970ies, where in FORTRAN 60, the first letter of a variable name determined its type to integer, when it was an I, J, L, M or N. However, should work now.

**Comment by vvoovv** [comment]
It's nearly there. The last attribute _face_ should be lowercased.

**Comment by vvoovv** [comment]
> Usually, parsers care about syntax, but not semantics. 

That's quite a usual matter for CSS.
For example:
```css
div {
    display: block;
    overflow: hidden;
}
```

**Comment by polarkernel** [comment]
>  face should be lowercased.

Corrected. Once _example2.py_ runs correctly, I propose to replace _example.py_ by the new one. I didn't check the old again.

**Comment by polarkernel** [comment]
> That's quite a usual matter for CSS.

I never came clear with CSS, it remains an abomination for me.  :-(

**Comment by vvoovv** [comment]
We are very close.
The last part should be:
```python
        faces = Value(Conditional(
            lambda item: item.footprint.getStyleBlockAttr("roofShape") in ("dome", "onion"),
            Constant(smoothness.Smooth)
        ))
```

**Comment by polarkernel** [comment]
> The last part should be:

OK, next attempt ready.

**Comment by vvoovv** [comment]
It works! That's a milestone! Congratulations!

I'll add the rest of styles from [default.py](https://github.com/vvoovv/blender-osm/blob/dev/style/default.py).

I moved the example styles to the subfolder [examples](https://github.com/vvoovv/pml/tree/master/examples).

**Comment by vvoovv** [comment]
I started the style [residential](https://github.com/vvoovv/pml/blob/master/examples/base.pml#L92) and got a strange result:

```python
]"residential" : [
    Meta(
        buildingUse = ,
        Constant("appartments"),
        buildingLaf = ,
        Constant("modern"),
        height = ,
        Constant("high rise")
    )

]
```

There is no comma before the key `residential`
`Constant(..)` should be used only inside `Value(..)`

**Comment by polarkernel** [comment]
> ... got a strange result

The translator works with several state variables to control the construction of the attributes. It seems that one of them has not been correctly reset. I did a lot of patches the last time and I like to review the translator and create a clean and straight forward solution, as now I know much more about the required output. This may take a day, or so.

**Comment by vvoovv** [comment]
Ok.

**Comment by polarkernel** [comment]
Given the PML statement
```
    levelHeight = random_normal( 3. );
```

which of the Python results is correct?
```
a)    levelHeight = Value(RandomNormal( 3. ))
or
b)    levelHeight = Value(RandomNormal( Constant(3.) ))
```
I assume b), because the 3. is in a function, but I am not sure.

**Comment by vvoovv** [comment]
a) is the correct one:
`levelHeight = Value( RandomNormal(3.) )`

`Constant(..)` is used inside the `Alternatives(..)` and `Conditional(..)`.

**Comment by vvoovv** [comment]
The output for the faces should be
```python
        faces = Value(Conditional(
            lambda item: item.footprint.getStyleBlockAttr("roofShape") in ("dome", "onion"),
            Constant(smoothness.Smooth)
        ))
```
instead of `Constant("smooth")` in the last line.

**Comment by polarkernel** [comment]
Was one of those days. Many interruptions caused the structure of my ideas always to collapse like a house of cards. Should have noted this building first in PML.

I commited a completely revised coder. Now, its your ball again.

**Comment by vvoovv** [comment]
Sorry, I am unable to run either of examples from the folder [examples](https://github.com/vvoovv/pml/tree/master/examples).

**Comment by polarkernel** [comment]
Me, I am sorry! There was a commented line remaining, that I used for debugging. Removed now, coder should work.

**Comment by vvoovv** [comment]
I am integrating the PML translator to the blender-osm addon. PML repo is incuded to the blender-osm addon as a submodule. I tried to translate the file _base.pml_ and got a Python syntax error in the line 45 of the output Python file. I think there is an extra round bracket in the _Conditional(..)_ clause:

```python
            claddingColor = Value(Alternatives(
                FromAttr("building:colour", FromAttr.Color),
                Conditional(
                    lambda item: item.getStyleBlockAttr("claddingMaterial") == "brick",
                    RandomWeighted( (((0.647,0.165,0.165,1.),1),((0.98,0.502,0.447,1.),1),((0.502,0.,0.,1.),1)) )
                )),
                Conditional(
                    lambda item: item.getStyleBlockAttr("claddingMaterial") == "plaster",
                    RandomWeighted( (((1.,0.627,0.478,1.),1),((0.565,0.933,0.565,1.),1),((1.,0.855,0.725,1.),1)) )
                )),
                Conditional(
                    lambda item: item.getStyleBlockAttr("claddingMaterial") == "glass",
                    RandomWeighted( (((0.306,0.447,0.573,1.),1),((0.169,0.318,0.361,1.),1),((0.094,0.18,0.271,1.),1)) )
                ))
            ))
```

**Comment by polarkernel** [comment]
Corrected.

**Comment by vvoovv** [comment]
Good news. I was able to load the style _examples/base.pml_ in the blender-osm addon.

Not that good news. I forgot to include _per_building(..)_ in the style and got the error after including it:
`Error on line 20, col 28: no viable alternative at input 'per_building(attr("building:material")|'`

**Comment by polarkernel** [comment]
I like the good news! Bad news are corrected, alternatives weren't accepted by grammar.

Question: Should <if( condition ) result;> also accept alternatives as result?

**Comment by vvoovv** [comment]
> Question: Should <if( condition ) result;> also accept alternatives as result?

There is no example for that case right now. But let's assume that it's possible.

**Comment by polarkernel** [comment]
> There is no example for that case right now. But let's assume that it's possible.

OK, I changed that.

**Comment by vvoovv** [comment]
Still an error on _examples/base.pml_:

`Error on line 42, col 1: no viable alternative at input 'per_building(attr("building:colour")|if(item["claddingMaterial"]=="brick")random_weighted(((0.647,0.165,0.165,1.),1),((0.98,0.502,0.447,1.),1),((0.502,0.,0.,1.),1))|if(item["claddingMaterial"]=="plaster")random_weighted(((1.,0.627,0.478,1.),1),((0.565,0.933,0.565,1.),1),((1.,0.855,0.725,1.),1))|if(item["claddingMaterial"]=="glass")random_weighted(((0.306,0.447,0.573,1.),1),((0.169,0.318,0.361,1.),1),((0.094,0.18,0.271,1.),1)))'`

**Comment by polarkernel** [comment]
> Still an error on examples/base.pml:

Alternatives for <if( condition ) result;> removed. I will check later why it made this error.

**Comment by polarkernel** [comment]
`if( condition ) result;` accepts now definitively alternatives as result.

**Comment by vvoovv** [comment]
Finally the style _high rise_ from examples/base.pml has been loaded. Congratulations!

![image](https://user-images.githubusercontent.com/613295/83453968-18530400-a464-11ea-9763-77b861ef5eac.png)

**Comment by vvoovv** [comment]
I will convert the other styles from _default.py_ to PML.

**Comment by polarkernel** [comment]
Great! Comgratulations from my side! I'll stay on standby, should more bugs arise.

**Comment by vvoovv** [comment]
Is it possible to support colors as described [here](https://github.com/vvoovv/pml/issues/8#issuecomment-633657852)?

**Comment by polarkernel** [comment]
> Is it possible to support colors as described here?

Quite complicated. Questions:
- Shall all four variants described there get translated to the Python tuple?
- Will the Python tuple become a _Constant()_ , where now for instance _yellow_ gets a constant?

```
            claddingColor = Value(Alternatives(
                Constant( "yellow" ),
                Conditional(
                    lambda item: item.a == item.b,
                    Constant( (1., 1., 0., 1.) )    # <-- for instance here?
                )
            ))
```

**Comment by vvoovv** [comment]
> * Shall all four variants described there get translated to the Python tuple?

Yes. What are the most difficult cases?

> * Will the Python tuple become a _Constant()_ , where now for instance _yellow_ gets a constant?
> 
> ```
>             claddingColor = Value(Alternatives(
>                 Constant( "yellow" ),
>                 Conditional(
>                     lambda item: item.a == item.b,
>                     Constant( (1., 1., 0., 1.) )    # <-- for instance here?
>                 )
>             ))
> ```

It should be
```python
            claddingColor = Value(Alternatives(
                Constant( (1., 1., 0., 1.) ),
                Conditional(
                    lambda item: item.a == item.b,
                    Constant( (1., 1., 0., 1.) )    # <-- for instance here?
                )
            ))
```
The color behaves as the other constants like a number or a string.

**Comment by polarkernel** [comment]
Difficulties are here to be solved, don't care, let me try.

**Comment by vvoovv** [comment]
I added the other styles ("residential", "place of worship", "man made") to _examples/base.pml_.

**Comment by polarkernel** [comment]
Let's give a try! It's best if you try all applications of colors you like to have and then we'll see if I got all of them. Hope I didn't produce side effects. As for other variables, I didn't implement a value check for colors. If I shall do it, please propose a the procedure (exception, ...) for this.

**Comment by vvoovv** [comment]
I tried the following:
```css
	claddingColor: per_building(
		attr("building:colour")
		|
		// plaster
		random_weighted(
	        (brown, 1),
	        (salmon, 1),
	        (maroon, 1)
		)
	);
```
got strings instead of tuples:
```python
            claddingColor = PerBuilding(Value(Alternatives(
                FromAttr("building:colour", FromAttr.Color),
                RandomWeighted( (("brown",1),("salmon",1),("maroon",1)) )
            )))
```

**Comment by vvoovv** [comment]
I assumed that the translator translated those string values into tuples or raised an error if something isn't correct with the color constants in PML.

I understand that it's a demanding task to translate all occurances of color constants in PML.

**Comment by polarkernel** [comment]
I will correct that. I have no more time today and will continue tomorrow,

**Comment by polarkernel** [comment]
It was really a very difficult task, but after some deep exercises in regex patterns, most of the color types should get replaced correctly now. Values in _rgb()_ and _rgba()_ do not get checked, similar to most other values. Incorrect hex color codes throw an exception (either by parser of by coder). Let's see how close to the finish line we are now.

**Comment by vvoovv** [comment]
About rgb() and rgba(). If that's too dificult, let's remove them.

I think a typical use case is just use a predefined color (red, orange, etc) or copy a hex from graphical editor. Its tedious to copy rgb values for _rgb()_ one by one.

**Comment by polarkernel** [comment]
> About rgb() and rgba(). If that's too dificult, let's remove them.

They are implemented, only their values do not get checked. One could for instance write _rgb(355,128,0)_ and the 355 would not throw an exception. I could implement it, but, as for most other values, one could also write _levels : -5_, without exception.

**Comment by vvoovv** [comment]
Ok. I'll check it later today.

**Comment by vvoovv** [comment]
Could you please round each number in the tuple resulting from conversion of a hex to 3 digits after the dot?

**Comment by vvoovv** [comment]
Incorrect output for examples/base.pml:

```python
                Conditional(
                    lambda item: item.getStyleBlockAttr("claddingMaterial") == "plaster",
                    RandomWeighted( (((1.0, 0.627, 0.478, 1.0),1),("light"(0.0, 0.502, 0.0, 1.0),1),((1.0, 0.855, 0.725, 1.0),1)) )
                ),
```

Note the string "light" in the _RandomWeighted_ line.

**Comment by polarkernel** [comment]
> round each number

> Incorrect output for examples/base.pml:

Both fixed.

**Comment by vvoovv** [comment]
Maybe you noticed there was a contribution from @Zkir

**Comment by vvoovv** [comment]
Great! It works! Thank you so much!

**Comment by polarkernel** [comment]
Great! A first contribution of mine that gets finished. I am very happy!
@Zkir : You're welcome!

**Comment by Zkir** [comment]
@polarkernel, thank you!

Guys, could you please discuss, do we really need to describe attributes in Dictionaries.py?

There are a lot of tags in OSM, and users may want to use many of them in PLM, as conditions for example.

**Comment by vvoovv** [comment]
The popular attributes should be in _Dictionaries.py_. Later the PML function _attr(..)_ could have optional parameters to avoid the loopkup in _Dictionaries.py_.

**Comment by Zkir** [comment]
But what for  this look up is needed anyway?

**Comment by vvoovv** [comment]
To get the translated code like below
```python
roofShape = Value( FromAttr("roof:shape", FromAttr.String, RoofShapes) ),
roofHeight = Value( FromAttr("roof:height", FromAttr.Float, FromAttr.NonNegative) )
```

**Comment by vvoovv** [comment]
A possible solution: if an attribute is not in _Dictionaries.py_, consider that the attribute has the _string_ type:
```python
myAttr = Value( FromAttr("unknownAttr", FromAttr.String) )
```

**Comment by polarkernel** [comment]
Unknown attribute gets _string_ type implemented in _Dictionaries.py_.

**Comment by Zkir** [comment]
@polarkernel, thank you!

@vvoovv, I see. So it's needed for type conversion.
It could be not so easy, because we need to interpret tag value in some complex way.
Here what I had for conversion of **height** and **start date**

height can be in feet, there are some elaborate conventions for approximate date:

1. https://github.com/Zkir/VFR_LANDMARKS_3D_RU/blob/master/OsmParser/main.py#L292
2. https://github.com/Zkir/VFR_LANDMARKS_3D_RU/blob/master/OsmParser/main.py#L308

**Comment by vvoovv** [comment]
Not sure if start date is need in the PML grammar.

**Comment by Zkir** [comment]
start date (building construction date) defines architectural style (look and feel, "laf"), if **building:architecture** tag is missing.
https://github.com/Zkir/VFR_LANDMARKS_3D_RU/blob/master/OsmParser/main.py#L374

So it could be very important.

**Comment by vvoovv** [comment]
I think it's only the year that matters.
So we probably need:
```css
constructionYear: year( attr("start:date") );
```

**Comment by vvoovv** [comment]
The line
```css
claddingColor: blue;
```
is translated to
```python
claddingColor = "blue"
```
instead of
```python
claddingColor = (0., 0., 1., 1.)
```
See examples/place_of_worship.pml

**Comment by polarkernel** [comment]
Glitch in color name replacement fixed.

**Comment by vvoovv** [comment]
It works now. Thank you!

**Comment by vvoovv** [comment]
Problems with [examples/house.pml](https://github.com/vvoovv/pml/blob/master/examples/house.pml):

The line numbers below refer to the PML file.

Line 4: "single family" instead of "single_family"

Line 15: `use = ("house_type_"1,)` instead of `use = ("house_type_1",)`. And similar problems in the other similar line

Line 89: `claddingMaterial =             FromStyleBlockAttr("f0CladdingMaterial",FromStyleBlockAttr.Footprint),`. Looks like extra white spaces are inserted. Not a real problem.

**Comment by polarkernel** [comment]
> Problems with house.pml:

All fixed.

**Comment by vvoovv** [comment]
Thanks!

**Comment by vvoovv** [comment]
I am introducing the concept of _class_: #13 
Could you please translate the attribute _class_ to _cl_ due to the problem described at #13 ?

**Comment by polarkernel** [comment]
> I am introducing the concept of class: #13
Could you please translate the attribute class to cl due to the problem described at #13 ?

Done

**Comment by vvoovv** [comment]
> Done

Thank you!

**Comment by vvoovv** [comment]
The following Python syntaxis for the conditions doesn't work:
a < item.width < b
a <= item.width < b
a < item.width <= b
a <= item.width <= b

**Comment by vvoovv** [comment]
Would it be possible to add the function [bldgAttr(..)](https://github.com/vvoovv/pml/issues/14)?

**Comment by polarkernel** [comment]
> The following Python syntaxis for the conditions doesn't work:

Fixed. Didn't even know that chained comaprisons are allowed in Python. Learning every day ;-)

**Comment by polarkernel** [comment]
> Would it be possible to add the function bldgAttr(..)?

Implemented.

**Comment by vvoovv** [comment]
> > The following Python syntaxis for the conditions doesn't work:
> 
> Fixed. Didn't even know that chained comaprisons are allowed in Python. Learning every day ;-)

Just tested it. Works perfectly! Thanks!

**Comment by vvoovv** [comment]
> > Would it be possible to add the function bldgAttr(..)?
> 
> Implemented.

The attached PML file does not work.
[bldg_attr.txt](https://github.com/vvoovv/pml/files/4915117/bldg_attr.txt)

**Comment by polarkernel** [comment]
> The attached PML file does not work.
bldg_attr.txt

In #14, the request was

> buildingAttr(attr) should be mapped to FromBldgAttr(..) with exactly the same parameters as FromAttr(..)

which made me implementing buildingAttr(attr) instead of bldgAttr(attr). Changed now to the second.

**Comment by vvoovv** [comment]
Sorry for the confusion. It works now!

Thank you so much!

**Comment by vvoovv** [comment]
`roof_tiles` in the attached PML is parsed to `Constant("roof tiles")` instead of `Constant("roof_tiles")`

[roof_tiles.txt](https://github.com/vvoovv/pml/files/4942358/roof_tiles.txt)

**Comment by polarkernel** [comment]
> roof_tiles in the attached PML is parsed to Constant("roof tiles") instead of Constant("roof_tiles")

Fixed.

**Comment by vvoovv** [comment]
> Fixed.

It works now. Thanks.

**Comment by vvoovv** [comment]
`roof_tiles` is still translated to `roof tiles` in the attached PML file:

[roof_tiles.txt](https://github.com/vvoovv/pml/files/4953029/roof_tiles.txt)

**Comment by polarkernel** [comment]
> roof_tiles is still translated to roof tiles in the attached PML file:

Fixed. I pray that there are not much more of these occurences.

**Comment by vvoovv** [comment]
> Fixed. I pray that there are not much more of these occurences.

I hope as well. It works. Thank you!

**Comment by vvoovv** [comment]
To be continued at https://github.com/prochitecture/pml/issues/4
